google_application_credentials="~/.config/gcloud/application_default_credentials.json"
google_project_id="ctrl-358804"
zone_dns_name="dsp.garvan.org.au"
deployment_subdomain="elsa-data-dev"
postgres_user="postgres"
elsa_data_image="gcr.io/ctrl-358804/elsa-data:dev"
